name: MalCon GitHub

# Controls when the action will run
on:
  push:
    branches: master

jobs:
  build:
    # The type of runner that the job will run on
    name: build github webpages
    runs-on: ubuntu-latest
    container: 
     image: myominnoo/tidyverse:dev0.1
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: render index files
        run: |
            bash ./scripts/render_index.sh "main" 
