
on:
  push:
    branches: master

name: MalCon GitHub

jobs:
  build:
    name: build github webpages
    runs-on: ubuntu-latest
    container: 
     image: myominnoo/dashboard:prod
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: render index files
        run: |
            bash ./scripts/render_index.sh "main" 
